name: Acme-emcA
version: 0.05
abstract: Acme::emcA
author: Audrey Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  perl: 5.004
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.42
